---
title: "Tools for regional planning and climate change mitigation: application of emission factors from the fourth national inventory to the ecological-economic zoning of Mato Grosso do Sul"
date: 2025-05-12
author:
  - name: Fernando Rodrigues Teixeira Dias
    orcid: 0000-0002-3739-0036
    corresponding: true
    email: fernando.dias@embrapa.br
    roles:
      - Investigation
      - Software
      - Visualization
    affiliations:
      - Embrapa
  - name: Catia Urbanetz
    email: catia.urbanetz@embrapa.br
    orcid: 0000-0001-8834-5959
    corresponding: false
    roles:
      - Supervision
    affiliations:
      - Embrapa
  - name: Pedro R. Andrade
    email: pedro.andrade@inpe.br
    orcid: 0000-0001-8675-4046
    corresponding: false
    roles:
      - Supervision
    affiliations:
      - INPE
  - name: Guilherme Malafaia
    roles:
      - Project administration
    affiliations:
      - Embrapa
keywords: 
  - greenhouse gases
  - land use 
  - land-use change
  - land cover
  - public polycies

plain-language-summary: |
  This work seeks to adapt estimates from the Fourth National Inventory of Emissions and Removals of Greenhouse Gases from Land Use, Land-Use Change, and Forests to the Economic and Ecological Zoning of Mato Grosso do Sul using land-use class maps that are more recent than those available in the Fourth National Inventory. To this end, annual average emission factors per hectare per biome and municipality were estimated from the Fourth National Inventory by grouping the 26 classes used by the Fourth National Inventory into six: Forests, Grasslands or Pasture, Agriculture, Wetlands, Built-up Area, Other. From the results, it is concluded that the proposed process is useful, even with the simplified mapping to six classes, but we recommend that there be a specialization of the Forest and the Grasslands or Pasture classes, not necessarily in the same subclasses as the Fourth National Inventory, but distinguishing at least native forest (managed or unmanaged) from secondary forest or reforestation, and woody formations from non-woody ones in the Grasslands or Pasture class.
key-points:
- The study adapts Brazil's greenhouse gas emission estimates to Mato Grosso do Sul state's ecological-economical zoning.
- Emission factors were estimated by consolidating 26 land-use classes into six broader categories.
- The simplified mapping is useful, but further differentiation within Forest and Grasslands/Pasture classes is recommended. 
crossref:
  chapters: true
execute:
  enabled: true
  echo: false
  eval: true
  output: false
  warning: true
  error: true
format:
  docx:
    toc: false
    number-sections: true
    number-depth: 3
    highlight-style: github
    reference-doc: custom-reference-doc.docx
  html:
    toc: false
    number-sections: true
    number-depth: 3
    highlight-style: github
ipynb-shell-interactivity: all
jupyter: python3
filters:
  - abstract-section
editor:
  markdown:
    wrap: none
bibliography: references.bib
---

# Supplementary file

This file was prepared as a Quarto Document using Python code, so, it is a pre-req that you know how to use Python in Quarto documents.

Suggestions and contributios are welcome and must be sent to the first author.

Before the first run:

-   Install Python packages: pandas numpy geopandas shapely pyogrio pyarrow matplotlib scipy ipython

-   Define a local path for inventory files under the path you downloaded this file, download the inventory files to it and set the inventory_file_path variable accordinggly.

-   Define another local path for intermediate results under the path you downloaded this file and set the results_file_path variable accordinggly.

Each step correspond to a Python cell code. The first cell code defines global variables (inventory_file_path, map_file_path, borders_file_path, results_file_path and others), loads the necessary Python libraries, define functions used in more than one cell, and should be run in every session. Each cell depends on the previous ones in the first execution, but will depend only on the first cell after the first execution of the first ones, because intermediary results for each cell are saved in results_file_path.

## First step

Execute it every session.

```{python}

# File path for shape files from IV Inventario Nacional.
inventory_file_path = r"D:\CiCarne\FUNDECT_MS_ZERO\PAB\inventory\Shapes_UF\\"

# File path for 2001, 2021, ZEE and municipalities polygons.
map_file_path = r"D:\CiCarne\FUNDECT_MS_ZERO\PAB\map_2001_2021\map_2001_2021\\"

# File path for 2001, 2021, ZEE and municipalities polygons.
borders_file_path = r"D:\CiCarne\FUNDECT_MS_ZERO\PAB\borders\\"

# File path for intermediary results.
results_file_path = r"results\\"

# Importing Pyhrton packages

import time
from datetime import datetime

import os
from pathlib import Path
import glob
import zipfile
import shutil

import pandas as pd
import numpy as np

import geopandas as gpd
from shapely.geometry import Point, LineString, Polygon, MultiPoint, MultiLineString, MultiPolygon
from shapely.validation import make_valid
import pyogrio
import pyarrow

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap 
from matplotlib.patches import Patch

from scipy.interpolate import interp1d

from IPython.display import display

# "Flag" to print many validations. Turn it to false to silent those prints.
verbose = True

# Functions used more in more than one code cell

def fix_geoms(gdf):
  
  mask_invalid = ~gdf.geometry.is_valid

  if (n1 := len(gdf[mask_invalid])) == 0:
    if verbose: print(f"All {len(gdf)} geometries are valid, at {datetime.now().strftime('%H:%M:%S')}.")

  else:
    gdf.loc[mask_invalid, 'geometry'] = gdf.loc[mask_invalid, 'geometry'].apply(lambda geom: make_valid(geom))
    mask_invalid = ~gdf.geometry.is_valid
    if (n2 := len(gdf[mask_invalid])) == 0:
      if verbose: print(f"All {len(gdf)} geometries are now valid, including the {n1} initially invalid ones, at {datetime.now().strftime('%H:%M:%S')}.")
    else:
      if verbose: print(f"Out of the {len(gdf)} geometries, {n1} were initially invalid, and {n2} geometries are still not valid, at {datetime.now().strftime('%H:%M:%S')}.")

def key_intersection(gdf1, gdf2, isolation_key):

  gdf1_keys = gdf1[isolation_key].drop_duplicates().values.tolist()
  if verbose: print('gdf1_keys', gdf1_keys)

  intersection_gdf = {}

  for key1 in gdf1_keys:
    group1 = gdf1.copy()
    group2 = gdf2.copy()

    for i, k1 in enumerate(isolation_key):
      group1 = group1[group1[k1] == key1[i]]
      group2 = group2[group2[k1] == key1[i]]

    if not group2.empty:

      by_columns = [col for col in group1.columns if col != 'geometry']
      if verbose: print('by_columns', by_columns)
      group1 = group1.dissolve(by=by_columns).reset_index()
      fix_geoms(group1)
      group1.sindex
      by_columns = [col for col in group2.columns if col != 'geometry']
      group2 = group2.dissolve(by=by_columns).reset_index()
      fix_geoms(group2)
      group2.sindex
      intersection = gpd.overlay(group1, group2, how='intersection', keep_geom_type=True)      
      intersection = intersection[~intersection.is_empty]

      if len(intersection) != 0:
        fix_geoms(intersection)
        intersection.sindex
        if verbose: print(key1, len(intersection), f"às {datetime.now().strftime('%H:%M:%S')}.")        
        intersection_gdf[tuple(key1)] = intersection

  return pd.concat(intersection_gdf.values(), ignore_index=True)

def weighted_quantile_linear(values, weights, quantile):
  """
  Calculates the specified quantile of a list of values with associated weights.

  Args:
    values: A list of numerical values.
    weights: A list of weights corresponding to the values. 
             Must have the same length as values.
    quantile: The desired quantile (between 0 and 1).

  Returns:
    The calculated quantile value.
  """

  # Sort values and corresponding weights in ascending order
  sorted_indices = np.argsort(values)
  values = np.array(values)[sorted_indices]
  weights = np.array(weights)[sorted_indices]

  # Calculate cumulative weights
  cumulative_weights = np.cumsum(weights)

  # Find the index of the first value where the cumulative weight exceeds the quantile
  target_weight = quantile * np.sum(weights)
  idx = np.searchsorted(cumulative_weights, target_weight, side='right')

  # Handle edge cases:
  if idx == 0:
    return values[0]
  elif idx == len(values):
    return values[-1]

  # Perform linear interpolation
  weight_below = cumulative_weights[idx - 1]
  weight_above = cumulative_weights[idx]
  value_below = values[idx - 1]
  value_above = values[idx]
  return value_below + (target_weight - weight_below) * (value_above - value_below) / (weight_above - weight_below)

def apply2(group2, lowest_quantile = 0.025, highest_quantile = 0.975, weighted_quantile = weighted_quantile_linear):

  unique_areas = group2[['fe', 'area_ha', 'duration']]

  weights = unique_areas['duration'] * unique_areas['area_ha']
  total_weights = weights.sum()
  weights = weights / total_weights

  average_fe = np.average(unique_areas['fe'], weights=weights)

  sorted_fe_with_index = unique_areas[['fe']].sort_values('fe')
  sorted_fe = sorted_fe_with_index['fe']
  cumulative_weights = weights[sorted_fe_with_index.index].cumsum()

  min_fe = unique_areas['fe'].min()
  max_fe = unique_areas['fe'].max()

  fe_list = sorted_fe.tolist()
  weight_list = weights.tolist()

  lo = max(min_fe, weighted_quantile(fe_list, weight_list, lowest_quantile))
  q1 = max(min_fe, weighted_quantile(fe_list, weight_list, 0.25))
  median = weighted_quantile(fe_list, weight_list, 0.5)
  q3 = min(max_fe, weighted_quantile(fe_list, weight_list, 0.75))
  hi = min(max_fe, weighted_quantile(fe_list, weight_list, highest_quantile))

  total_area = total_weights/(2016-1994)

  rows_count = len(unique_areas)

  return pd.Series({
    'min': min_fe,
    'lo': lo,
    'q1': q1,
    'avg': average_fe,
    'med': median,
    'q3': q3,
    'hi': hi,
    'max': max_fe,
    'area_ha': total_area,
    'rows': rows_count})

def apply1(group1):

  all_areas = []
  year_list = ['1994', '2002', '2010', '2016']

  for i, year in enumerate(year_list):
    if i > 0:
      year_ini = year_list[i-1]
      ipccgr_ini_col = 'ipccgr_'+year_ini
      year_fin = year_list[i]
      ipccgr_fin_col = 'ipccgr_'+year_fin
      period = year_ini[2:4]+year_fin[2:4]
      fe_col = 'fe_'+period
      el_col = 'el_'+period

      areas = (group1[[ipccgr_ini_col, ipccgr_fin_col, fe_col, 'area_ha']]
        .rename(columns={
          ipccgr_ini_col: 'ipccgr_ini', 
          ipccgr_fin_col: 'ipccgr_fin', 
          fe_col: 'fe'}))
      
      if areas.empty: continue
      areas['duration'] = int(year_fin) - int(year_ini)
      all_areas.append(areas)

  if len(all_areas) == 0: return

  all_areas = pd.concat(all_areas, ignore_index = True)

  return all_areas.groupby(['ipccgr_ini', 'ipccgr_fin'], observed=True).apply(apply2, include_groups=False)

# Functions for boxplots

def ipcc_label(row):

  ipcc_label = {
    'Agricultura': 'Ag',
    'Campo ou Pastagem': 'Cp',
    'Floresta': 'Fl',
    'Área construída': 'Ac',
    'Áreas alagadas': 'Al',
    'Outros': 'Ou'}

  return f"{ipcc_label.get(row['ipccgr_ini'], row['ipccgr_ini'])} -> {ipcc_label.get(row['ipccgr_fin'], row['ipccgr_fin'])}"

def plot_boxplot_grid(df, lo = 'lo', hi = 'hi', x_label_func=ipcc_label, y_label= "Emission factors (ton Co2eq/ha/year)", y_fontsize = 12, x_fontsize = 12, y_tick_fontsize = 12, title_font_size = 12):
  """
  Plots a grid of boxplots based on data in a Pandas DataFrame.

  Args:
    df: A Pandas DataFrame with columns 'ZEE', 'IPCC', 'min', 'lo', 'q1', 'avg', 'med', 'q3', 'hi', 'max'.
    x_label_func: A function to generate labels for the boxplots. Defaults to the 'label' function.
  """

  df = df[(df['min']!=0) | (df['max']!=0)] 
  df = df.rename(columns={'SIGLA':'ZEE'})
  df['label'] = df.apply(x_label_func, axis=1)
  df = df.sort_values(by=['ZEE', 'avg'], ascending=[True, False])

  zee_categories = sorted(df['ZEE'].unique())
  n_zees = len(zee_categories)

  subplots_per_column = 2
  fig, axes = plt.subplots(
    (n_zees + 1) // subplots_per_column if n_zees > 1 else 1, 
    subplots_per_column, 
    figsize=(20, 30))
  axes = axes.flatten()

  for i, zee in enumerate(zee_categories):
    zee_data = df[df['ZEE'] == zee]
    labels = zee_data['label'].tolist()
    box_stats = []
    for index, data in zee_data.iterrows():
      box_stats.append({
        'label': data['label'],
        'mean': data['avg'],
        'med': data['med'],
        'facecolor': 'red',
        'edgecolor': 'red',
        'mediancolor': 'black',
        'medianwidth': 20,
        'q1': data['q1'],
        'q3': data['q3'],
        'whislo': data[lo],
        'whishi': data[hi],
        'fliers': [],
      })

    axes[i].bxp(
      box_stats,
      showmeans=True, meanline=True,
      meanprops=dict(
        linewidth=2,
        linestyle='--', 
        color='red'),  
      medianprops=dict(
        color='black', 
        linewidth=2),
      showfliers=False)
    axes[i].set_title(f"{zee}", fontsize = title_font_size)
    axes[i].set_xticklabels(labels, rotation=45, ha='right', fontsize = x_fontsize)
    axes[i].set_ylabel(y_label, fontsize = y_fontsize)
    axes[i].tick_params(axis='y', labelsize=y_tick_fontsize)
    axes[i].yaxis.get_offset_text().set_fontsize(y_tick_fontsize)

  plt.tight_layout()
  plt.show()
```

## Getting Emissions from the Fourth National Inventory for Mato Grosso do Sul

In this step we load emissions data from the Fourth National Inventory for Mato Grosso do Sul in each of the three biomes that occur in MS, selecting the columns of interest, add the six IPCC classes corresponding to the 26 classes used by the Fourth National Inventory, and calculate the average annual emission factors per hectare for each record read from the Fourth National Inventory, saving GeoDataFrame with it.

```{python}
gdfs = []
category_cols = ['bioma', 'mun_geocod', 'cagr_1994', 'cagr_2002', 'cagr_2010', 'cagr_2016']
value_cols = ['el_9402',	'el_0210', 'el_1016', 'area_ha']

file_name = inventory_file_path + r"Produtos_MS_"

for bioma in ['Cerrado', 'Mata_Atlantica', 'Pantanal']:
  gdf = gpd.read_file(file_name + bioma + '.shp', 
    engine="pyogrio", use_arrow=True, encoding="latin1")

  if 'num_geocod' in gdf.columns: 
    gdf = gdf.rename(columns={'num_geocod': 'mun_geocod'})
    
  gdf = gdf[category_cols + value_cols + ['geometry']]
  for col in category_cols: gdf[col] = gdf[col].astype('category')
  for col in value_cols: gdf[col] = gdf[col].astype(float)

  gdfs.append(gdf)

gdf = pd.concat(gdfs, ignore_index = True)
fix_geoms(gdf)

ipcc_group = pd.DataFrame([
  {'ipccgr': 'Floresta', 'cagr': 'FNM'}, 
  {'ipccgr': 'Floresta', 'cagr': 'FM'}, 
  {'ipccgr': 'Floresta', 'cagr': 'FSec'}, 
  {'ipccgr': 'Floresta', 'cagr': 'Ref'}, 
  {'ipccgr': 'Floresta', 'cagr': 'CS'}, 
  {'ipccgr': 'Campo ou Pastagem', 'cagr': 'OFLNM'}, 
  {'ipccgr': 'Campo ou Pastagem', 'cagr': 'OFLM'}, 
  {'ipccgr': 'Campo ou Pastagem', 'cagr': 'OFLSec'}, 
  {'ipccgr': 'Campo ou Pastagem', 'cagr': 'GNM'}, 
  {'ipccgr': 'Campo ou Pastagem', 'cagr': 'GM'}, 
  {'ipccgr': 'Campo ou Pastagem', 'cagr': 'GSec'}, 
  {'ipccgr': 'Campo ou Pastagem', 'cagr': 'Ap'}, 
  {'ipccgr': 'Campo ou Pastagem', 'cagr': 'APD'}, 
  {'ipccgr': 'Agricultura', 'cagr': 'Ac'}, 
  {'ipccgr': 'Agricultura', 'cagr': 'PER'}, 
  {'ipccgr': 'Agricultura', 'cagr': 'CANA'}, 
  {'ipccgr': 'Área construída', 'cagr': 'S'}, 
  {'ipccgr': 'Áreas alagadas', 'cagr': 'A'}, 
  {'ipccgr': 'Áreas alagadas', 'cagr': 'Res'}, 
  {'ipccgr': 'Outros', 'cagr': 'DnNM'}, 
  {'ipccgr': 'Outros', 'cagr': 'DnM'}, 
  {'ipccgr': 'Outros', 'cagr': 'ArNM'}, 
  {'ipccgr': 'Outros', 'cagr': 'ArM'}, 
  {'ipccgr': 'Outros', 'cagr': 'Min'}, 
  {'ipccgr': 'Outros', 'cagr': 'SE'}, 
  {'ipccgr': 'Outros', 'cagr': 'NO'}])

for col in ipcc_group.columns: ipcc_group[col] = ipcc_group[col].astype('category') 

ipcc_merge = ipcc_group.rename(columns={'cagr': 'cagr_2016', 'ipccgr': 'ipccgr_2016'})
gdf = pd.merge(gdf, ipcc_merge, on='cagr_2016')
ipcc_merge = ipcc_group.rename(columns={'cagr': 'cagr_2010', 'ipccgr': 'ipccgr_2010'})
gdf = pd.merge(gdf, ipcc_merge, on='cagr_2010')
ipcc_merge = ipcc_group.rename(columns={'cagr': 'cagr_2002', 'ipccgr': 'ipccgr_2002'})
gdf = pd.merge(gdf, ipcc_merge, on='cagr_2002')
ipcc_merge = ipcc_group.rename(columns={'cagr': 'cagr_1994', 'ipccgr': 'ipccgr_1994'})
gdf = pd.merge(gdf, ipcc_merge, on='cagr_1994')

gdf['fe_1016'] = gdf['el_1016'] / gdf['area_ha'] / (2016-2010)   
gdf['fe_0210'] = gdf['el_0210'] / gdf['area_ha'] / (2010-2002)  
gdf['fe_9402'] = gdf['el_9402'] / gdf['area_ha'] / (2002-1994)

MS_products_gdf = gdf.copy()
MS_products_gdf.to_file(results_file_path + r"MS_products_gdf.gpkg", driver="GPKG")
```

## Checking totals

In this step we produce two pivot tables similar to the Fourth Inventory spreadsheets for MS, period 2010-2016, for testing purposes only.

```{python}
if verbose:
  def in_format(x):
      if pd.isna(x) or x == 0: return ''
      else: return "{:,.1f}".format(x/1e3)

  for col in ['el_1016', 'area_ha']:
    print(gdf.pivot_table(
      values=col, 
      index=['ipccgr_2010', 'cagr_2010'], 
      columns=['ipccgr_2016', 'cagr_2016'], 
      aggfunc='sum',
      margins=True,
      margins_name='Total',
      observed=True)
    .map(in_format))
```

## Find Fourth National Inventory records not assigned to municipalities

In this step we find geometries from the Fourth National Inventory for MS without municipality identification, that is, with 'mun_geocod' not informed. This results are used in the research article Materials and Method section.

```{python}
MS_products_gdf = gpd.read_file(results_file_path + r"MS_products_gdf.gpkg", engine="pyogrio", use_arrow=True)

no_mun_geocod = (MS_products_gdf['mun_geocod'] == '0') | MS_products_gdf['mun_geocod'].isna()

summary = pd.DataFrame(
  [
    {
      'area_ha': MS_products_gdf['area_ha'].sum(),
      'el_1016': MS_products_gdf['el_1016'].sum(),
      'el_0210': MS_products_gdf['el_0210'].sum(),
      'el_9402': MS_products_gdf['el_9402'].sum()
    },
    {
      'area_ha': MS_products_gdf[no_mun_geocod]['area_ha'].sum(),
      'el_1016': MS_products_gdf[no_mun_geocod]['el_1016'].sum(),
      'el_0210': MS_products_gdf[no_mun_geocod]['el_0210'].sum(),
      'el_9402': MS_products_gdf[no_mun_geocod]['el_9402'].sum()
    }
  ],
  index=['todos', 'sem município']
).apply(lambda x: x/1e3)

summary.loc['porcentagem'] = (summary.loc['sem município'] / summary.loc['todos'] * 100)
summary.map("{:,.3f}".format)
```

## Filter Fourth National Inventory records not assigned to municipalities

In this step we select only the records with a valid municipality code. In addition, the current CRS in the Fourth Inventory is geographic, and we estimated a suitable CRS for projections and area calculation for the next steps, but keeping the areas reported in the Fourth Inventory for the purpose of estimating the average emission factors in each area. Polygons are corrected after these adjustments.

```{python}
MS_products_gdf = gpd.read_file(results_file_path + r"MS_products_gdf.gpkg", engine="pyogrio", use_arrow=True)
gdf = MS_products_gdf[~no_mun_geocod]

if verbose: print ('CRS available in the "shapefile" files of the Fourth National Inventory:', gdf.crs)
estimated_crs = gdf.estimate_utm_crs()

if verbose: print('Estimated CRS for MS for intersection and area calculation:', estimated_crs)
gdf = gdf.to_crs(estimated_crs)

fix_geoms(gdf)
gdf.sindex

fixed_MS_products_gdf = gdf.copy()
gdf.to_file(results_file_path + r"fixed_MS_products_gdf.gpkg", driver="GPKG")
```

## Overlaying ZEE with Data from the Fourth National Inventory

In this step we overlay the ZEE-MS polygons with those from the Fourth National Inventory.

```{python}
gdf = gpd.read_file(borders_file_path + r"zee\zee.dbf", engine="pyogrio", use_arrow=True)
gdf['SIGLA'] = gdf['SIGLA'].astype('category')
gdf = gdf.drop([ 'ID', 'ZONAS', 'AREA_KILOM', 'HECTARES', 'PERIMETER_', 'LONGITUDE',
  'ACRES', 'AREA_KIL_1', 'PERIMETER1', 'AREA_KIL_2', 'PERIMETER2',
  'AREA_KIL_3', 'PERIMETER3', 'AREA_KIL_4', 'PERIMETER4', 'AREA_METER',
  'PERIMETER5', 'AREA_MET_1', 'PERIMETER6', 'AREA_MET_2', 'PERIMETER7', 'area'], axis=1)

fix_geoms(gdf)
gdf.sindex

MS_ZEE_gdf = gdf.copy()
MS_ZEE_gdf.to_file(results_file_path + r"MS_ZEE_gdf.gpkg", driver="GPKG")
```

## Recalculating areas and calculating emission factors

In this step we recalculate the areas of the polygons resulting from the overlay of the ZEE-MS to the records of the Fourth National Inventory and recalculate the emissions from the average annual emission factors per hectare for each record read from the Fourth National Inventory.

```{python}
fixed_MS_products_gdf = gpd.read_file(results_file_path + r"fixed_MS_products_gdf.gpkg", engine="pyogrio", use_arrow=True)

MS_ZEE_gdf = gpd.read_file(results_file_path + r"MS_ZEE_gdf.gpkg", engine="pyogrio", use_arrow=True)

gdf = gpd.overlay(
  fixed_MS_products_gdf,
  MS_ZEE_gdf.to_crs(fixed_MS_products_gdf.crs), 
  how='intersection', 
  keep_geom_type=True)

fix_geoms(gdf)
gdf.sindex

gdf['area_ha'] = gdf['geometry'].area/1e4
gdf['el_1016'] = gdf['fe_1016'] * gdf['area_ha'] * (2016-2010)   
gdf['el_0210'] = gdf['fe_0210'] * gdf['area_ha'] * (2010-2002)  
gdf['el_9402'] = gdf['fe_9402'] * gdf['area_ha'] * (2002-1994)  

MS_ZEE_products_gdf = gdf.copy()
MS_ZEE_products_gdf.to_file(results_file_path + r"MS_ZEE_products_gdf.gpkg", driver="GPKG")
```

## Checking totals until now

In this step we check totals just for test.

```{python}
if verbose:

  MS_ZEE_gdf = gpd.read_file(results_file_path + r"MS_ZEE_gdf.gpkg", 
    engine="pyogrio", use_arrow=True)
  fixed_MS_products_gdf = gpd.read_file(results_file_path + r"fixed_MS_products_gdf.gpkg", 
    engine="pyogrio", use_arrow=True)
  MS_products_gdf = gpd.read_file(results_file_path + r"MS_products_gdf.gpkg", 
    engine="pyogrio", use_arrow=True)
  MS_ZEE_products_gdf = gpd.read_file(results_file_path + r"MS_ZEE_products_gdf.gpkg",
    engine="pyogrio", use_arrow=True)

  print('MS_ZEE_gdf, CRS lido:', MS_ZEE_gdf.crs, ', CRS estimado:', MS_ZEE_gdf.estimate_utm_crs(), ', CRS usado:', fixed_MS_products_gdf.crs)

  for gdf in [MS_products_gdf, fixed_MS_products_gdf, MS_ZEE_products_gdf]:
    print('area_ha', gdf['area_ha'].sum())

  for gdf in [fixed_MS_products_gdf, MS_ZEE_products_gdf]:
    print('geometry.area/1e4', gdf['geometry'].area.sum()/1e4)

  for el in ['el_9402', 'el_0210', 'el_1016']:
    for gdf in [MS_products_gdf, fixed_MS_products_gdf, MS_ZEE_products_gdf]:
      print('gdf.el',  gdf[el].sum())
```

## Calculating average factors for IPCC classes by ZEE, biome, municipality

In this step we calculate average annual net emission factors per ha per IPCC land use class change in the total inventory, for each ZEE,biome and municipality, and some basic statistics for qualitative assessment of the uncertainty added when the detail of the 26 classes used by the Fourth National Inventory is lost.

```{python}
MS_ZEE_emission_factors_df = (MS_ZEE_products_gdf
  .groupby(['SIGLA', 'bioma', 'mun_geocod'], observed=True)
  .apply(apply1, include_groups=False)
  .reset_index())

MS_ZEE_emission_factors_df.to_csv(results_file_path + r"emissions\MS_ZEE_emission_factors_df.csv", index=False)
```

## Calculating average factors for IPCC classes by ZEE only

In this step we do the same ofthe previous step, by ZEE only

```{python}
MS_ZEE_products_gdf = gpd.read_file(results_file_path + r"MS_ZEE_products_gdf.gpkg", engine="pyogrio", use_arrow=True)

MS_ZEE_1994_2016_emissions_df = (MS_ZEE_products_gdf
  .groupby(['SIGLA'], observed=True)
  .apply(apply1, include_groups=False)
  .reset_index())

MS_ZEE_1994_2016_emissions_df.to_csv(results_file_path + r"emissions\MS_ZEE_1994_2016_emissions_df.csv", index=False)
```

## Checking totals again

In this step we check totals just for test.

```{python}
if verbose:

  MS_ZEE_gdf = gpd.read_file(results_file_path + r"MS_ZEE_gdf.gpkg", 
    engine="pyogrio", use_arrow=True)
  fixed_MS_products_gdf = gpd.read_file(results_file_path + r"fixed_MS_products_gdf.gpkg", 
    engine="pyogrio", use_arrow=True)
  MS_products_gdf = gpd.read_file(results_file_path + r"MS_products_gdf.gpkg", 
    engine="pyogrio", use_arrow=True)
  MS_ZEE_products_gdf = gpd.read_file(results_file_path + r"MS_ZEE_products_gdf.gpkg",
    engine="pyogrio", use_arrow=True)
  MS_ZEE_emission_factors_df = pd.read_csv(results_file_path + r"emissions\MS_ZEE_emission_factors_df.csv")

  for gdf in [
    MS_products_gdf, fixed_MS_products_gdf, MS_ZEE_products_gdf, MS_ZEE_emission_factors_df]:
    print(gdf['area_ha'].sum())

  for gdf in [MS_products_gdf, fixed_MS_products_gdf, MS_ZEE_products_gdf]:
    print(gdf['el_9402'].sum() + gdf['el_0210'].sum() + gdf['el_1016'].sum())

  el_avg = MS_ZEE_emission_factors_df['avg'] * MS_ZEE_emission_factors_df['area_ha'] * (2016-1994)
  print(el_avg.sum())

  df = MS_ZEE_emission_factors_df
  print(len(df[
    (df['min'] > df['lo'])  |
    (df['lo']  > df['q1'])  |
    (df['q1']  > df['med']) |
    (df['q3']  < df['med']) |
    (df['hi']  < df['q3'])  |
    (df['max'] < df['hi'])  |
    (df['min'] > df['avg']) |
    (df['max'] < df['avg'])]))
```

## Total emisison statistics

In this step we calculate statistics for total emissions using statistics for emission factos and polygon areas.

```{python}
MS_ZEE_emission_factors_df = pd.read_csv(results_file_path + r"emissions\MS_ZEE_emission_factors_df.csv")

df = MS_ZEE_emission_factors_df.copy()
for col in ['min', 'lo', 'q1', 'avg', 'med', 'q3', 'hi', 'max']: 
  df[col] = df[col] * df['area_ha']

MS_ZEE_emission_totals_df = (df
  .groupby(['SIGLA', 'ipccgr_ini', 'ipccgr_fin'], observed = True)
  [['min', 'lo', 'q1', 'avg', 'med', 'q3', 'hi', 'max']].sum()
  .reset_index())

MS_ZEE_emission_totals_df.to_csv(results_file_path + r"emissions\MS_ZEE_emission_totals_df.csv", index=False)
```

## Figure 2

In this step we produce Figure 2 of article Results.

```{python}
MS_ZEE_1994_2016_emissions_df = pd.read_csv(results_file_path + r"emissions\MS_ZEE_1994_2016_emissions_df.csv")

plot_boxplot_grid(MS_ZEE_1994_2016_emissions_df, lo='min', hi='max', x_fontsize=16, y_fontsize=16, y_tick_fontsize = 16, title_font_size = 16)
```

## Reading municipalities of MS

```{python}
gdf = gpd.read_file(borders_file_path + 'municipalities//MS_Municipios_2022.dbf', engine="pyogrio", use_arrow=True)
gdf['CD_MUN'] = gdf['CD_MUN'].astype('category')

gdf = gdf.to_crs(gdf.estimate_utm_crs())
fix_geoms(gdf)
gdf.sindex

gdf.to_file("MS_Municipios_gdf.gpkg", driver="GPKG")
MS_Municipios_gdf = gdf.copy()
```

## Overlaying ZEE to municipalities of MS

```{python}
MS_ZEE_gdf = gpd.read_file(results_file_path + r"MS_ZEE_gdf.gpkg", engine="pyogrio", use_arrow=True)
gdf = gpd.overlay(MS_Municipios_gdf, MS_ZEE_gdf.to_crs(MS_Municipios_gdf.crs), how='intersection', keep_geom_type=True)
fix_geoms(gdf)
gdf.sindex
MS_ZEE_municipios_gdf = gdf.copy()
MS_ZEE_municipios_gdf.to_file(results_file_path + "MS_ZEE_municipios_gdf.gpkg", driver="GPKG")
```

## Overlaying Biomes to ZEE and municipalities of MS

```{python}
gdf = gpd.read_file(borders_file_path + 'biomes//lm_bioma_250.dbf', engine="pyogrio", use_arrow=True)
gdf['Bioma'] = gdf['Bioma'].astype('category')
gdf = gdf.drop(['CD_Bioma'], axis=1)
gdf = gdf.to_crs(MS_ZEE_municipios_gdf.crs)
fix_geoms(gdf)
gdf.sindex

gdf = gpd.overlay(gdf, MS_ZEE_municipios_gdf, how='intersection', keep_geom_type=True)
fix_geoms(gdf)
gdf.sindex
gdf['area_ha'] = gdf['geometry'].area/1e4

Biomas_ZEE_Municipios_gdf = gdf.copy()
Biomas_ZEE_Municipios_gdf.to_file(results_file_path + "Biomas_ZEE_Municipios_gdf.gpkg", driver="GPKG")
```

## Reading MS 2001 and 2021 mappings

```{python}
gdf_file_list = [
  { 'year': '2001',
    'path': map_file_path + r"2001\classification_2001.shp"}, 
  { 'year': '2021',
    'path': map_file_path + r"2021\classification_2021.shp"}]

for gdf_file in gdf_file_list:
  print(f"Reading {gdf_file['year']} at {datetime.now().strftime("%H:%M:%S")}.")
  gdf = gpd.read_file(gdf_file['path'], engine="pyogrio", use_arrow=True)

  print(f"Calculating area of {gdf_file['year']} at {datetime.now().strftime("%H:%M:%S")}.")
  gdf['CLASS'] = gdf['CLASS'].astype('category')
  gdf = gdf.to_crs(gdf.estimate_utm_crs())
  fix_geoms(gdf)
  gdf.sindex
  gdf[f'area_ha'] = gdf['geometry'].area/1e4

  print(f"Saving {gdf_file['year']} at {datetime.now().strftime("%H:%M:%S")}.")
  gdf.to_file(results_file_path + f"maps//classification_{gdf_file['year']}.gpkg", driver="GPKG")
```

## Overlaying ZEE, biomes, and municipalities to 2001 and 2021 mappings

```{python}
Biomas_ZEE_Municipios_gdf = gpd.read_file(results_file_path + f"Biomas_ZEE_Municipios_gdf.gpkg", engine="pyogrio", use_arrow=True)

for year in ['2001','2021']:
  gdf = gpd.read_file(results_file_path + f"maps//classification_{year}.gpkg", engine="pyogrio", use_arrow=True)
  gdf = gdf.rename(columns={'CLASS': f"CLASS_{year}"})
  gdf = gpd.overlay(Biomas_ZEE_Municipios_gdf, gdf, how='intersection', keep_geom_type=True)
  gdf = gdf.drop(
    ['NM_MUN', 'SIGLA_UF', 'AREA_KM2', 'area_ha_1', 'area_ha_2'], axis=1)
  fix_geoms(gdf)
  gdf.sindex
  gdf['area_ha'] = gdf['geometry'].area/1e4
  gdf.to_file(results_file_path + f"maps//classification_{year}_mun.gpkg", driver="GPKG")
```

## Calculating land use change from 2001 e 2021 mappings, per ZEE, biomes and municipalities

This step is specially heavy, so we saved their results in Zenodo.

```{python}
classification_2001_mun = gpd.read_file(results_file_path + 'maps\\classification_2001_mun.gpkg', engine="pyogrio", use_arrow=True)

classification_2021_mun = gpd.read_file(results_file_path + 'maps\\classification_2021_mun.gpkg', engine="pyogrio", use_arrow=True)

zee_list = sorted(classification_2001_mun['SIGLA'].unique())
for zee in zee_list:

  if verbose: print(f"Starting intersections for {zee} at {datetime.now().strftime('%H:%M:%S')}.")

  gdf_2001 = classification_2001_mun[classification_2001_mun['SIGLA'] == zee].drop(['area_ha'], axis=1)
  gdf_2021 = classification_2021_mun[classification_2021_mun['SIGLA'] == zee].drop(['area_ha'], axis=1)

  mun_list = sorted(gdf_2001['CD_MUN'].unique())
  first = True
  for mun in mun_list:
    gdf = key_intersection(
      gdf_2001[gdf_2001['CD_MUN'] == mun], 
      gdf_2021[gdf_2021['CD_MUN'] == mun], 
      ['SIGLA', 'Bioma', 'CD_MUN'])
    
    gdf = gdf.drop(['Bioma_2', 'CD_MUN_2', 'SIGLA_2'], axis=1)
    gdf = gdf.rename(columns={'Bioma_1':'Bioma', 'CD_MUN_1':'CD_MUN', 'SIGLA_1': 'SIGLA'}) 
    gdf.sindex
    gdf['area_ha'] = gdf['geometry'].area/1e4

    if first:
      if verbose: print(f"Saving first file for {mun} in {zee} at {datetime.now().strftime('%H:%M:%S')}.")
      gdf.to_file(results_file_path + f"changes//change_2001_2021_{zee}.gpkg", driver="GPKG")
      first = False
    else:
      if verbose: print(f"Saving another file for {mun} in {zee} at {datetime.now().strftime('%H:%M:%S')}.")
      gdf.to_file(results_file_path + f"changes//change_2001_2021_{zee}.gpkg", driver="GPKG", mode='a')

  if verbose: print(f"Ended intersections for {zee} at {datetime.now().strftime('%H:%M:%S')}.")
```

## Setting annual emission factors

```{python}
ipcc_group_before = ['agua e area umida', 'assentamento urbano', 'floresta', 'lavoura', 'outros', 'pastagem']
ipcc_group_after = ['Áreas alagadas', 'Área construída', 'Floresta', 'Agricultura', 'Outros', 'Campo ou Pastagem']

df = pd.read_csv(
  results_file_path + r"emissions\MS_ZEE_emission_factors_df.csv",
  dtype={
    'bioma': str,
    'mun_geocod': 'category',
    'SIGLA': 'category',
    'ipccgr_ini': 'category',
    'ipccgr_fin': 'category',
    'min': float,
    'lo': float,
    'q1': float,
    'avg': float,
    'med': float,
    'q3': float,
    'hi': float,
    'max': float,
    'area_ha': float,
    'rows': int}
    ).drop(['rows', 'area_ha'], axis=1)

df['bioma'] = df['bioma'].replace('Mata Atlantica', 'Mata Atlântica').astype('category')

emissions_2001_2021_df = pd.DataFrame(columns=df.columns)

zee_list = sorted(df['SIGLA'].unique())
for zee in zee_list:

  if verbose: print(f"Reading changes from {zee} às {datetime.now().strftime('%H:%M:%S')}.")

  gdf = gpd.read_file(results_file_path + f"changes//change_2001_2021_{zee}.gpkg", engine="pyogrio", use_arrow=True)

  if verbose: print(f"Fixing names for classes in {zee} às {datetime.now().strftime('%H:%M:%S')}.")

  gdf['CLASS_2001'] = gdf['CLASS_2001'].replace(ipcc_group_before, ipcc_group_after)
  gdf['CLASS_2021'] = gdf['CLASS_2021'].replace(ipcc_group_before, ipcc_group_after)

  if verbose: print(f"Applying factors to areas in {zee} às {datetime.now().strftime('%H:%M:%S')}.")

  gdf = pd.merge(
    gdf, df[df['SIGLA'] == zee],
      left_on=['SIGLA', 'Bioma', 'CD_MUN', 'CLASS_2001', 'CLASS_2021'],
      right_on=['SIGLA', 'bioma', 'mun_geocod', 'ipccgr_ini','ipccgr_fin'])

  for col in ['min', 'lo', 'q1', 'avg', 'med', 'q3', 'hi', 'max']: gdf[col] = gdf[col] * gdf['area_ha']

  emissions_2001_2021_df = pd.concat([
    emissions_2001_2021_df, 
    gdf.drop(['geometry'], axis=1)], 
    ignore_index=True)
  
  if verbose: print(f"{zee} finished at {datetime.now().strftime('%H:%M:%S')}.")

df = (emissions_2001_2021_df
  .groupby(['SIGLA', 'ipccgr_ini', 'ipccgr_fin'], observed=True)
  [['min', 'lo', 'q1', 'avg', 'med', 'q3', 'hi', 'max', 'area_ha']].sum()
  .sort_values(by=['SIGLA', 'avg'], ascending=[True, False])
  .reset_index())

emissions_2001_2021_total_df = df.copy()
emissions_2001_2021_total_df.to_csv(results_file_path + r"emissions\emissions_2001_2021_total_df.csv", index=False)
```

## Table 2

In this step we calculate Table 2 of article's Results.

```{python}
df = pd.read_csv(results_file_path + r"emissions\emissions_2001_2021_total_df.csv")
category_order = ["Floresta", "Campo ou Pastagem", "Agricultura", "Áreas alagadas", "Área construída", "Outros"]
df['ipccgr_ini'] = pd.Categorical(df['ipccgr_ini'], categories=category_order, ordered=True)
df['ipccgr_fin'] = pd.Categorical(df['ipccgr_fin'], categories=category_order, ordered=True)

(df.pivot_table(
  observed=True,
  values='area_ha', 
  index=['ipccgr_ini', 'ipccgr_fin'], 
  columns='SIGLA', 
  aggfunc='sum')
  .rename_axis(columns='ZEE', index=['2001', '2021'])
  .fillna(0)
  .map(lambda y: '-' if y == 0 else str("{:,.1f}".format(y))
    .replace('.', ';').replace(',', '.').replace(';', ',')))
```

## Figure 3

In this step we calculate Figure 3 of article's Results.

```{python}
emissions_2001_2021_total_df = pd.read_csv(results_file_path + r"emissions\emissions_2001_2021_total_df.csv")

plot_boxplot_grid(emissions_2001_2021_total_df, lo='min', hi='max', y_label = "Emissions (ton CO2eq/year)", x_fontsize=16, y_fontsize=16, y_tick_fontsize = 16, title_font_size = 16)
```

## Figure 4

In this step we calculate Figure 4 of article's Results.

```{python}
MS_ZEE_products_gdf = gpd.read_file(results_file_path + r"MS_ZEE_products_gdf.gpkg", engine="pyogrio", use_arrow=True)

gdf_list = []
year_list = ['1994', '2002', '2010', '2016']
for i, year in enumerate(year_list):
  if i > 0:
    year_ini = year_list[i-1]
    ipccgr_ini = 'ipccgr_'+year_ini
    cagr_ini = 'cagr_'+year_ini
    year_fin = year_list[i]
    ipccgr_fin = 'ipccgr_'+year_fin
    cagr_fin = 'cagr_'+year_fin
    period = year_ini[2:4]+year_fin[2:4]
    fe = 'fe_'+period
    el = 'el_'+period

    gdf = MS_ZEE_products_gdf.copy()
    gdf = (gdf[(gdf[el] > 0) &
      (gdf[ipccgr_fin] == gdf[ipccgr_ini]) &
      (gdf[ipccgr_ini].isin(['Floresta', 'Campo ou Pastagem']))]
      [['SIGLA', 'bioma', 'mun_geocod', 
      ipccgr_ini, cagr_ini, cagr_fin, fe, el, 'geometry']]
      .rename(columns={
        ipccgr_ini: 'ipccgr_ini', 
        cagr_ini: 'cagr_ini', 
        cagr_fin: 'cagr_fin', 
        fe: 'fe', 
        el: 'el'}))

    gdf['duration'] =  int(year_fin) - int(year_ini)
    gdf['area_ha'] = gdf.geometry.area/1e4
    gdf_list.append(gdf)

gdf = pd.concat(gdf_list, ignore_index = True)

df = (gdf
  .groupby(['SIGLA', 'ipccgr_ini','cagr_ini', 'cagr_fin'], observed=True)
  .apply(apply2, include_groups=False)
  .reset_index())

def cagr_label(row):

  ipcc_label = {
  'Agricultura': 'Ag',
  'Campo ou Pastagem': 'Cp',
  'Floresta': 'Fl',
  'Área construída': 'Ac',
  'Áreas alagadas': 'Al',
  'Outros': 'Ou'}

  return f"{ipcc_label.get(row['ipccgr_ini'], row['ipccgr_ini'])}:{row['cagr_ini']} -> {row['cagr_fin']}"

plot_boxplot_grid(df, lo='min', hi='max', x_label_func = cagr_label)
```